name: CI Validation

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Validation Placeholder
        run: echo "CI Validation workflow created"