name: DCM Plan
on:
  pull_request:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  dcm-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-actions@v3
        with:
          use-oidc: true

      - name: Verify OIDC Authentication
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: GITHUB_DCM_SVC
        run: |
          echo "User=$SNOWFLAKE_USER"
          echo "Account=$SNOWFLAKE_ACCOUNT"
          snow sql -q "select CURRENT_USER(),CURRENT_ROLE(),CURRENT_ACCOUNT()" -x

      - name: DCM Plan
        run: |
          snow dcm plan --target DEV -x 
      - name: Debug Variables
        run: |
          echo "Account=$SNOWFLAKE_ACCOUNT"
          echo "User=$SNOWFLAKE_USER"
