name: Terraform Plan

on:
  workflow_dispatch:

jobs:
 terraform-plan:
     runs-on: ubuntu-latest

     env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: GITHUB_TERRAFORM_SVC
        SNOWFLAKE_WORKLOAD_IDENTITY_PROVIDER: OIDC
     steps:
       - uses: actions/checkout@v4
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3

       - name: Terraform Init
         run: |
           cd terraform
           terraform init      
       - name: Show Terraform Environment
         run: |
           env | grep SNOWFLAKE
       - name: Terraform Validate
         run: |
           cd terraform
           terraform validate    

       - name: Terraform Plan
         run: |
           cd terraform
           terraform plan     