CREATE ROLE IF NOT EXISTS GITHUB_DEV_TERRAFORM_ROLE;
CREATE ROLE IF NOT EXISTS GITHUB_DEV_DCM_ROLE;
CREATE ROLE IF NOT EXISTS GITHUB_TEST_TERRAFORM_ROLE;
CREATE ROLE IF NOT EXISTS GITHUB_TEST_DCM_ROLE;

CREATE USER IF NOT EXISTS GITHUB_DEV_TERRAFORM_SVC
  TYPE = SERVICE;

CREATE USER IF NOT EXISTS GITHUB_DEV_DCM_SVC
  TYPE = SERVICE;

CREATE USER IF NOT EXISTS GITHUB_TEST_TERRAFORM_SVC
  TYPE = SERVICE;

CREATE USER IF NOT EXISTS GITHUB_TEST_DCM_SVC
  TYPE = SERVICE;

GRANT ROLE GITHUB_DEV_TERRAFORM_ROLE
  TO USER GITHUB_DEV_TERRAFORM_SVC;

GRANT ROLE GITHUB_DEV_DCM_ROLE
  TO USER GITHUB_DEV_DCM_SVC;

GRANT ROLE GITHUB_TEST_TERRAFORM_ROLE
  TO USER GITHUB_TEST_TERRAFORM_SVC;

GRANT ROLE GITHUB_TEST_DCM_ROLE
  TO USER GITHUB_TEST_DCM_SVC;

